name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 你的主分支，可以根据实际情况修改

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
          
      # Fix for https://github.com/gohugoio/hugo/issues/9810
      - name: Git config
        run: git config --global core.quotepath false

      - name: Build
        run: hugo --minify --cleanDestinationDir --gc

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages  # deploying branch
